[Bugfix] Launcher3: Do not allow widgets to have 1 row as minimum size
This reverts commit ca430c1937531952aa51385393c33f977ba28228.

* Fixes launcher crash when trying to add a widget in a homescreen without space

FATAL EXCEPTION: main
Process: com.android.launcher3, PID: 4993
java.lang.IllegalArgumentException: width & height must be > 0
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1388)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1364)
	at com.android.launcher3.icons.BitmapRenderer.createHardwareBitmap(BitmapRenderer.java:52)
	at com.android.launcher3.Workspace.createWidgetDrawable(Workspace.java:2927)
	at com.android.launcher3.Workspace.animateWidgetDrop(Workspace.java:3008)
	at com.android.launcher3.Workspace.onDropExternal(Workspace.java:2860)
	at com.android.launcher3.Workspace.onDrop(Workspace.java:2015)
	at com.android.launcher3.dragndrop.DragController.drop(DragController.java:539)
	at com.android.launcher3.dragndrop.DragController.onDriverDragEnd(DragController.java:386)
	at com.android.launcher3.dragndrop.DragDriver$InternalDragDriver.onTouchEvent(DragDriver.java:188)
	at com.android.launcher3.dragndrop.DragController.onControllerTouchEvent(DragController.java:438)
	at com.android.launcher3.views.BaseDragLayer.onTouchEvent(BaseDragLayer.java:270)
	at android.view.View.performOnTouchCallback(View.java:16266)
	at android.view.View.dispatchTouchEvent(View.java:16223)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3119)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2792)
	at com.android.launcher3.views.BaseDragLayer.dispatchTouchEvent(BaseDragLayer.java:305)
	at com.android.launcher3.dragndrop.DragLayer.dispatchTouchEvent(DragLayer.java:227)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3125)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2806)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3125)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2806)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3125)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2806)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3125)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2806)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:496)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1953)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4510)
	at com.android.launcher3.Launcher.dispatchTouchEvent(Launcher.java:2050)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:454)
	at android.view.View.dispatchPointerEvent(View.java:16548)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7564)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7326)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6723)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6780)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6746)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6912)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6754)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6969)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6727)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6780)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6746)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6754)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6727)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9831)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9782)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9751)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9973)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:295)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:349)
	at android.os.Looper.loopOnce(Looper.java:189)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)